# Generated by Django 3.2 on 2022-05-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('bike_model', models.CharField(max_length=254)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_now', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('price_was', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=6, null=True)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100)),
                ('sizes', models.BooleanField(blank=True, default=False, null=True)),
                ('discipline', models.CharField(max_length=100, null=True)),
                ('material', models.CharField(max_length=100, null=True)),
                ('wheel_size', models.CharField(max_length=30, null=True)),
                ('rear_derailleur', models.CharField(max_length=100, null=True)),
                ('colour', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.classification')),
            ],
        ),
    ]
