# Generated by Django 3.2 on 2022-05-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frame_in_inches',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
