# Generated by Django 3.2 on 2022-04-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220416_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_now',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_was',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
