# Generated by Django 3.2 on 2022-04-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220416_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='frame_in_inches',
        ),
    ]
